import {
  ArrowRightIcon,
  InformationCircleIcon,
  EyeIcon,
  EyeSlashIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  PencilSquareIcon,
  XCircleIcon,
  XMarkIcon,
  ArchiveBoxXMarkIcon,
  MagnifyingGlassIcon,
  AdjustmentsHorizontalIcon,
  DocumentTextIcon,
  UserIcon,
  UserCircleIcon,
  ArrowLeftOnRectangleIcon,
  CameraIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  CodeBracketIcon,
} from "@heroicons/react/24/outline";
import { CurrencyDollarIcon } from "@heroicons/react/24/solid";

const Icon = {
  ArrowRight: ArrowRightIcon,
  Info: InformationCircleIcon,
  Eye: EyeIcon,
  EyeSlash: EyeSlashIcon,
  ChevronDownIcon: ChevronDownIcon,
  ChevronUpIcon: ChevronUpIcon,
  ChevronLeftIcon: ChevronLeftIcon,
  ChevronRightIcon: ChevronRightIcon,
  Edit: PencilSquareIcon,
  XCircle: XCircleIcon,
  Close: XMarkIcon,
  Delete: ArchiveBoxXMarkIcon,
  Search: MagnifyingGlassIcon,
  Money: CurrencyDollarIcon,
  Config: AdjustmentsHorizontalIcon,
  Document: DocumentTextIcon,
  User: UserIcon,
  UserCircle: UserCircleIcon,
  Logout: ArrowLeftOnRectangleIcon,
  Camera: CameraIcon,
  Code: CodeBracketIcon,
  Text: CodeBracketIcon,
};

export default Icon;
